In [1]:
import pandas as pd
import os
import pickle

In [2]:
csv_file_dir = r'C:\Users\Nick\Documents\GitHub\grvmodel\DATA\BetfairSPdata'
csv_files = os.listdir(csv_file_dir)
print(len(csv_files))
os.chdir(csv_file_dir)
csv_march = [f for f in csv_files if '032023.csv' in f]

1898

In [25]:
for i in csv_march:
    print(i)

01032023.csv
02032023.csv
03032023.csv
04032023.csv
05032023.csv

In [7]:
csv_files[-1]

'31122022.csv'

In [3]:
df = pd.concat((pd.read_csv(f, on_bad_lines='skip') for f in csv_files), ignore_index=True)

In [4]:
df['date'] = pd.to_datetime(df.EVENT_DT, dayfirst=True).dt.date

In [5]:
dates = pd.to_datetime(df.EVENT_DT, dayfirst=True).dt.date

In [6]:
dates.max()

TypeError: '>=' not supported between instances of 'datetime.date' and 'float'

In [7]:
dates

0          2017-12-31
1          2017-12-31
2          2017-12-31
3          2017-12-31
4          2017-12-31
              ...
3391518    2022-12-30
3391519    2022-12-30
3391520    2022-12-30
3391521    2022-12-30
3391522    2022-12-30
Name: EVENT_DT, Length: 3391523, dtype: object

In [8]:
df = df[df['BSP'].notnull()]
df["dog"] = df["SELECTION_NAME"].astype(str).str[2:]
df["loc"] = df['MENU_HINT'].str[0:3]
df.shape

(3121164, 37)

In [9]:
dfAus = df[(df['MENU_HINT'].str.contains("(AUS)"))|(df['MENU_HINT'].str.contains("(NZL)"))]
dfAus.shape

C:\Users\Nick\AppData\Local\Temp\ipykernel_14236\1269963096.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  dfAus = df[(df['MENU_HINT'].str.contains("(AUS)"))|(df['MENU_HINT'].str.contains("(NZL)"))]

(1653879, 37)

In [10]:
dfAus.date.max()

datetime.date(2023, 3, 14)

In [11]:
dfNZL = df[(df['loc']=="NZL")]

In [12]:
dfAus = dfAus[['EVENT_ID', 'EVENT_DT', 'SELECTION_ID', 'BSP','dog','MENU_HINT' ]]

In [13]:
os.chdir(r"C:\Users\Nick\Documents\GitHub\grvmodel\Python\DATA")
with open("df-betfairSP.npy", "wb") as fp:   #Pickling
    
    pickle.dump(dfAus, fp)

In [13]:
dates = pd.to_datetime(dfAus.EVENT_DT)

In [19]:
df[df['dog']==' Deelish Mags']

,EVENT_ID,MENU_HINT,EVENT_NAME,EVENT_DT,SELECTION_ID,SELECTION_NAME,WIN_LOSE,BSP,PPWAP,MORNINGWAP,...,morningwap,ppmax,ppmin,ipmax,ipmin,morningtradedvol,pptradedvol,iptradedvol,dog,loc
28208,195371199.0,TRP / Sheffield 28th Feb,A4 500m,28-02-2022 17:03,42016053.0,1. Deelish Mags,0.0,11.000000,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
241342,179983915.0,Sky Sports Racing / Sheff 2nd Mar,A6 500m,02-03-2021 19:41,38056015.0,2. Deelish Mags,0.0,3.900000,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,Sky
250652,197052848.0,TRP / Sheffield 2nd Apr,A5 500m,02-04-2022 21:48,38056015.0,2. Deelish Mags,0.0,13.063811,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
438414,177589709.0,TRP / Sheff 4th Jan,A5 500m,04-01-2021 14:04,38056015.0,2. Deelish Mags,0.0,10.500000,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
565052,194287195.0,TRP / Sheffield 5th Feb,A4 500m,05-02-2022 20:12,42016053.0,1. Deelish Mags,0.0,6.200000,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
601239,184157278.0,TRP / Sheffield 5th Jun,A6 500m,05-06-2021 19:58,38056015.0,2. Deelish Mags,0.0,6.540582,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
665310,193075490.0,TRP / Sheffield 6th Jan,A5 500m,06-01-2022 12:13,42016053.0,1. Deelish Mags,0.0,3.712573,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
914542,195781316.0,TRP / Sheffield 8th Mar,A5 500m,08-03-2022 20:46,42016053.0,1. Deelish Mags,0.0,11.000000,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
927795,183113139.0,Sky Sports Racing / Sheffield 8th May,A6 500m,08-05-2021 20:12,38056015.0,2. Deelish Mags,1.0,2.898328,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,Sky
1099969,192180398.0,TRP / Sheffield 9th Dec,A6 500m,09-12-2021 13:13,42016053.0,1. Deelish Mags,1.0,8.455358,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
1247835,180410510.0,TRP / Sheff 11th Mar,A6 500m,11-03-2021 14:19,37887241.0,3. Deelish Mags,0.0,7.370212,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
1460900,179276261.0,Sky Sports Racing / Sheff 13th Feb,A6 500m,13-02-2021 19:26,38056015.0,2. Deelish Mags,0.0,15.382772,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,Sky
1574094,194726466.0,TRP / Sheffield 14th Feb,A4 500m,14-02-2022 15:09,42016053.0,1. Deelish Mags,0.0,7.200000,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
1586232,196107418.0,TRP / Sheffield 14th Mar,A5 500m,14-03-2022 15:44,38056015.0,2. Deelish Mags,0.0,26.694003,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
1886209,192436845.0,TRP / Sheffield 16th Dec,A5 500m,16-12-2021 11:13,42016053.0,1. Deelish Mags,0.0,3.400000,1.0,3.599986,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
2360197,195062370.0,TRP / Sheffield 21st Feb,A4 500m,21-02-2022 14:19,42016053.0,1. Deelish Mags,0.0,13.350126,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
2460407,193695857.0,TRP / Sheffield 22nd Jan,A5 500m,22-01-2022 18:36,42016053.0,1. Deelish Mags,1.0,2.095703,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
2487789,196516176.0,TRP / Sheffield 22nd Mar,A5 500m,22-03-2022 19:58,42016053.0,1. Deelish Mags,0.0,8.000000,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
2588042,179676446.0,Sky Sports Racing / Sheff 23rd Feb,A6 500m,23-02-2021 21:31,38056015.0,2. Deelish Mags,0.0,5.408018,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,Sky
2677333,192670235.0,TRP / Sheffield 23rd Dec,A5 500m,23-12-2021 13:59,38056015.0,2. Deelish Mags,0.0,3.550000,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
3197784,177370804.0,TRP / Sheff 28th Dec,A5 500m,28-12-2020 14:04,37887241.0,3. Deelish Mags,0.0,4.500000,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP
3308275,178616282.0,RPGTV / Sheff 30th Jan,A6 500m,30-01-2021 20:46,37887241.0,3. Deelish Mags,0.0,6.200250,1.0,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,RPG
3356724,192870081.0,TRP / Sheffield 30th Dec,A5 500m,30-12-2021 11:13,42016053.0,1. Deelish Mags,0.0,2.481675,1.0,2.728252,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deelish Mags,TRP

: