In [2]:
import pandas as pd
import pickle
import os

In [32]:
os.getcwd()
os.chdir(r"C:\Users\Nick\Documents\GitHub\grvmodel\Python\DATA")
dog_stats_file = open( "dog_stats_df_FASTTRACK new margins.npy", 'rb')
dog_stats_file = pickle.load(dog_stats_file)
dog_stats_df = pd.DataFrame(dog_stats_file)

In [36]:
dogs_stats_for_r = dog_stats_df.drop(['dog_name', 'stats'], axis=1)

In [37]:
dog_stats_file.loc[dog_stats_file['place']==1, 'margin']=0
dog_stats_file.head(10)

,dogid,dog_name,raceid,race_grade,date,trackOHE,track_name,dist,stats,place,startprice,margin,bfSP,runtime
0,214382420,SUPERIOR POWER,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,"[4, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...",8.0,1.9,6.87,2.280000,19.87
1,302937173,SUPERIOR DUNKLEY,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,"[3, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...",7.0,37.3,5.74,28.858711,19.79
2,296096015,WORTHY PRINCE,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,"[6, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...",6.0,19.1,3.66,17.287920,19.64
3,296096016,ANNIHILATION,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,"[1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...",4.0,7.9,2.01,10.456086,19.53
4,291188717,THURSDAY THUNDER,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,"[8, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...",3.0,38.6,1.93,40.000000,19.52
5,314367487,RIO HUSTLER,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,"[2, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...",2.0,6.3,0.89,7.200000,19.45
6,314368991,CALLUM ARI,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,"[5, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...",1.0,11.5,0.00,19.500000,19.39
7,282125654,GRUMPY DEREK,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,"[7, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...",5.0,5.4,3.33,7.543589,19.62
8,328356413,CRAZY OLD BIRD,500539128,Maiden Final,2019-12-03,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Horsham,410.0,"[6, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...",8.0,14.6,19.74,11.000000,24.67
9,331308298,SILVER COMPASS,500539128,Maiden Final,2019-12-03,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Horsham,410.0,"[2, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, ...",7.0,40.6,15.69,110.000000,24.38

In [39]:
dogs_stats_for_r['implied probabilty'] = 1/dogs_stats_for_r['startprice']

In [40]:
dogs_stats_for_r

,dogid,raceid,race_grade,date,trackOHE,track_name,dist,place,startprice,margin,bfSP,runtime,implied probabilty
0,214382420,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,8.0,1.9,6.87,2.280000,19.87,0.526316
1,302937173,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,7.0,37.3,5.74,28.858711,19.79,0.026810
2,296096015,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,6.0,19.1,3.66,17.287920,19.64,0.052356
3,296096016,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,4.0,7.9,2.01,10.456086,19.53,0.126582
4,291188717,498695480,Mixed 6/7 Final,2019-12-01,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Healesville,350.0,3.0,38.6,1.93,40.000000,19.52,0.025907
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020502,592253144,849837292,Mixed 4/5,2022-12-01,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Ballarat,545.0,3.0,14.1,7.71,NaN,31.49,0.070922
1020503,514248946,849837292,Mixed 4/5,2022-12-01,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Ballarat,545.0,2.0,19.3,2.34,NaN,31.11,0.051813
1020504,472135386,849837292,Mixed 4/5,2022-12-01,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Ballarat,545.0,1.0,1.2,0.00,NaN,30.95,0.833333
1020505,592709127,849837292,Mixed 4/5,2022-12-01,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Ballarat,545.0,8.0,22.2,14.57,NaN,31.97,0.045045
1020506,558491864,849837292,Mixed 4/5,2022-12-01,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Ballarat,545.0,7.0,10.9,14.14,NaN,31.94,0.091743

In [42]:
dogs_stats_for_r.to_csv('dog_stats_for_r.csv')

In [15]:
file = open(r"C:\Users\Nick\Documents\GitHub\grvmodel\Python\pytorch\New Model\DATA\143k fasttrack FFNN.npy", "rb")
data = pickle.load(file)
# seperate out classes from inputs

raceIDs, inputs, classes, prices, margins, betfairSP,names = zip(*data)

In [24]:
prices_df = pd.DataFrame(prices)

In [29]:
prices_df.dropna(inplace=True)

In [30]:
prices_df

           0     1     2     3     4     5     6     7
0        7.9   6.3  37.3   1.9  11.5  19.1   5.4  38.6
1        1.3  40.6  50.8  24.3  14.3  14.6  20.4   5.6
2        4.6  43.3  93.9   2.0  14.4   5.9   6.6  18.1
3        7.2   3.7   2.2  20.5  15.2  35.9   6.6  22.7
4       13.6   6.1  10.8  29.4   2.6   7.0  19.2   4.0
...      ...   ...   ...   ...   ...   ...   ...   ...
142745   1.8  30.4  12.5  14.2   0.0  10.1   5.6   5.9
142746   3.3   5.5   4.9  24.0   5.4   6.8  74.8   9.2
142747  18.1   6.6   0.0   3.2  29.8   0.0   2.8   3.6
142748   1.3   8.3   8.4  21.3   0.0  24.4  15.5  31.2
142749  19.0   1.2  22.2  16.2  44.7  19.3  10.9  14.1

[140893 rows x 8 columns]